name: Ejecucion Diaria de Script

on:
  schedule:
    - cron: '13 06 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    # --- NUEVO PASO: Instalar Rclone ---
    - name: Instalar Rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    - name: Configurar archivo de Rclone
      run: |
        mkdir -p ~/.config/rclone
        cat << 'EOF' > ~/.config/rclone/rclone.conf
        ${{ secrets.RCLONE_CONF }}
        EOF

    - name: Crear carpetas de trabajo locales
      run: |
        mkdir -p datos_entrada
        mkdir -p datos_salida

    - name: Descargar CSVs de prueba (Input)
      # REEMPLAZA EL ID DE ABAJO por el ID de tu carpeta "Uber_Test_Entrada"
      run: |
        rclone copy "gdrive:" datos_entrada/ --drive-root-folder-id 1IM3FtnTroA3ofiKs7DX5z0HSiX4ssCqG -v

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install polars pyarrow

    - name: Ejecutar el procesamiento
      run: python proceso_completo_uber.py

    - name: Subir Resultados a Drive de prueba (Output)
      # REEMPLAZA EL ID DE ABAJO por el ID de tu carpeta "Uber_Test_Salida"
      run: |
        rclone copy datos_salida/ "gdrive:" --drive-root-folder-id 1VZIIp6HfmYmGTGTcsV0-4dJsYpxejic6 -v